BookManage/Book/urls.py
from django.conf.urls import url
from Book import views

urlpatterns = [
    url(r'^(\w+)/(\w+)/$', views.index),
    url(r'^property/$', views.property),
    url(r'^get/$', views.get),
    url(r'^get1/$', views.get1),
    url(r'^get2/$', views.get2),
    url(r'^post/$', views.post),
    url(r'^fan/$', views.fan),
    url(r'^fanafan /$', views.fan1, name='fan1'),
    url(r'^post1/$', views.post1),
    url(r'^set_session/$', views.set_session),
    url(r'^get_session/$', views.get_session),
    url(r'^add_num/(\w+)/(\w+)/$', views.add_num),
    url(r'^(\w+)/(\w+)/$', views.add),

]

BookManage/BookManage/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('Book.urls')),
    url(r'^', include('Book.urls', namespace='Book')),
    url(r'^tinymce/$', include('tinymce.urls'))
]

BookManage/Book/models.py
from django.db import models

from django.db import models
from tinymce.models import HTMLField


# 富文本编辑器
class GoodInfo(models.Model):
    gcontent = HTMLField(verbose_name='商品详情')

    class Meta:
        db_table = 'df_goods'
        verbose_name = '商品'
        verbose_name_plural = verbose_name

BookManage/Book/views.py
from django.shortcuts import render
from django.http import HttpResponse

# 从传来的request中提取参数
def index(request, v1, v2):
    # 构造上下文
    context = {'v1': v1, 'v2': v2}
    return render(request, 'Book/index.html', context)

def property(requeset):
    context = {'path':requeset.path, 'method': requeset.method, 'GET':requeset.GET}

    return render(requeset, 'Book/property.html', context)

def get(request):
    return render(request, 'Book/get.html')


def get1(request):
    dict = request.GET

    a = dict.get('a')
    b = dict.get('b')
    c = dict.get('c')

    context = {'a':a, 'b':b, 'c':c}
    return render(request, 'Book/get1.html', context)

def get2(request):
    dict = request.GET

    a = dict.getlist('a')
    b = dict.get('b')
    c = dict.get('c')

    context = {'a':a, 'b':b, 'c':c}
    return render(request, 'Book/get2.html', context)

# post请求的POST属性，准备表单
def post(request):
    return render(request, 'Book/post.html')


def fan(request):
    return render(request, 'Book/fan.html')


def fan1(request):
    return render(request, 'Book/fan1.html')
# 获取post表单中的信息，并且在网页展示
def post1(request):
    dict = request.POST
    uname = dict.get('uname')
    upassword = dict.get('password')
    sex = dict.get('sex')
    like = dict.getlist('like')

    context = {'uname':uname, 'upwd':upassword, 'sex':sex, 'like':like}
    return render(request, 'Book/post1.html', context)


# 服务器设置session
def set_session(request):
    request.session['h1'] = 'baiyujun'
    return HttpResponse('ok!')


# 获取已经设置的session信息
def get_session(request):
    res = request.session.get('h1')
    return HttpResponse(res)


def add_num(request, num1, num2):
    res = num1 + num2
    return HttpResponse(res)


def add(request, num1, num2):
    res = num1 * num2
    return HttpResponse(res)

BookManage/templates/Book/fan.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<a href="{% url 'Book:fan1' %}">反向解析</a>
</body>
</html>

BookManage/templates/Book/fan1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>反向解析成功</h1>
</body>
</html>

BookManage/templates/Book/get.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<a href="/get1/?a=10&b=20&c=python">一键一值</a>
<a href="/get2/?a=10&b=20&a=python">一键多值</a>
</body>
</html>

BookManage/templates/Book/get1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>{{ a }}</h1>
    <h1>{{ b }}</h1>
    <h1>{{ c }}</h1>
</body>
</html>

BookManage/templates/Book/get2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>{{ a }}</h1>
    <h1>{{ b }}</h1>
    <h1>{{ c }}</h1>
</body>
</html>

BookManage/templates/Book/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>vi:{{ v1 }}</h1>
    <h2>v2:{{ v2 }}</h2>
</body>
</html>

BookManage/templates/Book/peopleinfo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<ul>
    <li>{{ peoplelist }}</li>
</ul>
</body>
</html>

BookManage/templates/Book/post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="/post1/" method="post">

{# Django项目默认会做CSRF安全验证 #}
{% csrf_token %}

<input type="text" name="uname">
<br>
<br>
<input type="password" name="upassword">
<br>
<br>
<input type="radio" name="sex" value="男">男　<input type="radio" name="sex" value="女">女
<br>
<br>
<input type="checkbox" name="like" value="足球">足球　<input type="checkbox" name="like" value="篮球">篮球　<input type="checkbox" name="like" value="羽毛球">羽毛球
<br>
<br>
<input type="submit" value="提交">
</form>
</body>
</html>

BookManage/templates/Book/post1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>{{ uname }}</h1>
    <h1>{{ upwd }}</h1>
    <h1>{{ sex }}</h1>
    <h2>{{ like }}</h2>
</body>
</html>

BookManage/templates/Book/property.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>path:{{ path }}</h1>
    <h1>method:{{ method }}</h1>
    <h1>GET: {{ GET }}</h1>
</body>
</html>